### ISSUE TITLE
How do you get an access token?

### ISSUE THREAD

**Issue by tmaszk** [wfgilman/plaid-elixir#5]
Sorry, maybe this is obvious, but I've looked through the API and can't find a way to get an `access_token`.  I see how to rotate a token once I already have one, but not create one in the first place.

I have an account with plaid, and have enabled development access.

Can you help?

**Comment by wfgilman** [comment]
With Plaid's new API they are only allowing you to create Items using Plaid Link. When a user connects to his institution successfully, the client gets a single-use public token. That is then exchanges for an Item id and access token which should be stored. The function to exchange is `Plaid.Item.exchange_public_token/1`. 

It's inconvenient because you need to spin up a client and server to get things working. I think Plaid is trying to make Plaid Link a trusted, branded source for connecting securely to FIs.

I updated the README to reflect this.
